Repository DioxusLabs/taffy, pull requests merged in 2022-07, with the labels that each got.

#196 Use slotmap instead of bespoke arena, limiting to one parent only
  Cargo.toml
  RELEASES.md
  examples/basic.rs
  examples/nested.rs
  scripts/gentest/Cargo.toml
  src/data.rs
  src/error.rs
  src/flexbox.rs
  src/forest.rs
  src/indexmap.rs
  src/lib.rs
  src/node.rs
  src/style.rs
  src/sys.rs
Labels: code quality, breaking-change, performance

#206 Clarify documentation
  src/style.rs
Labels: documentation

#208 Move `hidden_layout()` to parent scope
  RELEASES.md
  src/flexbox.rs
  src/layout.rs
Labels: code quality

#209 Move flex-item and flex-line layout passes to methods instead of closures
  src/flexbox.rs
Labels: code quality

#210 Remove unused deps: hashbrown, hash32, typenum
  Cargo.toml
Labels: code quality, dependencies

#211 Remove unused licenses from DENY.tonl list
  deny.toml
Labels: build system
