Repository DioxusLabs/taffy, pull requests merged in 2022-11, with the labels that each got.

#244 Add deeper depth benchmarks
  benches/big_tree.rs
Labels: benchmarks

#252 Fix calling set_measure on a node that didn't previously have a measure func
  src/node.rs
Labels: bug

#253 Change signature of mark_dirty method to match taffy 0.1
  src/compute/mod.rs
  src/data.rs
  src/node.rs
  src/tree.rs
Labels: usability, breaking-change

#249 WIP: User-friendly release notes for 0.2
  README.md
  RELEASES.md
  benches/results-2022-11-23.md
Labels: documentation

#258 Don't specify explicit version for dev-dependencies
  Cargo.toml
  deny.toml
Labels: release

#259 Fix errant ) in RELEASES.md
  RELEASES.md
Labels: documentation

#260 Return iterator for children for `LayoutTree`
  RELEASES.md
  src/compute/flexbox.rs
  src/compute/mod.rs
  src/node.rs
  src/tree.rs
Labels: usability, breaking-change

#262 Min values should override max values
  RELEASES.md
  benches/generated/min_height_overrides_max_height.rs
  benches/generated/min_width_overrides_max_width.rs
  benches/generated/mod.rs
  src/math.rs
  test_fixtures/min_height_overrides_max_height.html
  test_fixtures/min_width_overrides_max_width.html
  tests/generated/min_height_overrides_max_height.rs
  tests/generated/min_width_overrides_max_width.rs
  tests/generated/mod.rs
  tests/min_max_overrides.rs
Labels: bug

#270 Make tree debug printing more readable
  src/debug.rs
Labels: usability, code quality
