Repository DioxusLabs/taffy, pull requests merged in 2022-06, with the labels that each got.

#75 Cleanup imports
  src/algo.rs
  src/forest.rs
  src/geometry.rs
  src/id.rs
  src/lib.rs
  src/node.rs
  src/number.rs
Labels: code quality

#84 Remove serde_camel_case and serde_kebab_case features
  Cargo.toml
  RELEASES.md
  src/geometry.rs
  src/number.rs
  src/style.rs
Labels: code quality

#87 Remove migration guide from PR template
  .github/pull_request_template.md
Labels: meta

#86 Make alloc and std compatible features
  Cargo.toml
  RELEASES.md
  src/sys.rs
Labels: bug, code quality

#94 Make order field of `Layout` pub
  RELEASES.md
  src/result.rs
Labels: usability, code quality, breaking-change

#95 Rename modules
  RELEASES.md
  src/flexbox.rs
  src/forest.rs
  src/id.rs
  src/layout.rs
  src/lib.rs
  src/node.rs
  src/prelude.rs
Labels: code quality

#105 Remove Allocator::free
  src/node.rs
Labels: code quality, performance

#107 Refactor Forest::mark_dirty for clarity
  src/forest.rs
Labels: code quality

#112 Remove dead Overflow type
  RELEASES.md
  src/prelude.rs
  src/style.rs
Labels: bug, usability, code quality

#108 Vendor indexmap from heapless crate
  Cargo.toml
  src/indexmap.rs
  src/lib.rs
  src/sys.rs
Labels: code quality

#116 Cleanup arguments
  src/node.rs
Labels: code quality

#125 Add `#[must_use]` to all static methods
  src/flexbox.rs
  src/forest.rs
  src/geometry.rs
  src/layout.rs
  src/node.rs
  src/number.rs
  src/sys.rs
Labels: code quality

#126 Fix #[allow(dead_code)] annotation
  src/indexmap.rs
Labels: code quality

#127 Use consistent import style in flexbox.rs
  src/flexbox.rs
Labels: code quality

#135 Bump releases to `0.2.0`
  Cargo.toml
  RELEASES.md
Labels: meta

#137 Stop leaking internal types in public interface
  RELEASES.md
  src/flexbox.rs
  src/sys.rs
Labels: documentation, code quality, breaking-change

#141 Remove gen-test script
  Cargo.toml
  scripts/gentest/Cargo.toml
  scripts/gentest/src/main.rs
  scripts/gentest/test_base_style.css
  scripts/gentest/test_helper.js
Labels: code quality

#139 Remove `ComputeResult` type
  src/flexbox.rs
  src/layout.rs
Labels: code quality

#143 Add allow(unused_code) annotations to methods in indexmap
  src/indexmap.rs
Labels: code quality, build system

#145 restore and fix gentest
  CONTRIBUTING.md
  Cargo.toml
  RELEASES.md
  scripts/gentest/Cargo.toml
  scripts/gentest/src/main.rs
  scripts/gentest/test_base_style.css
  scripts/gentest/test_helper.js
  src/flexbox.rs
  src/style.rs
  tests/generated/min_height.rs
  tests/generated/min_width.rs
  tests/generated/percentage_flex_basis_cross_min_height.rs
  tests/generated/rounding_flex_basis_flex_grow_row_prime_number_width.rs
  tests/generated/rounding_flex_basis_flex_grow_row_width_of_100.rs
  tests/generated/rounding_flex_basis_overrides_main_size.rs
  tests/generated/rounding_fractial_input_1.rs
  tests/generated/rounding_fractial_input_2.rs
  tests/generated/rounding_fractial_input_3.rs
  tests/generated/rounding_fractial_input_4.rs
Labels: bug, code quality, build system

#106 Return a Result from Taffy::remove
  RELEASES.md
  src/node.rs
  tests/node.rs
Labels: usability, breaking-change, blocked

#149 Mark generated files as lunguist-generated
  .gitattributes
Labels: build system

#150 Replace `#[allow(unused_code)]` with `#[allow(dead_code)]` in `indexmap.rs`
  src/indexmap.rs
Labels: code quality

#151 Minor docs fix in `flexbox.rs`
  src/flexbox.rs
Labels: documentation, code quality

#147 Improve error message when `chromedriver` is not installed
  scripts/gentest/src/main.rs
Labels: usability

#153 Remove serde renames from Display
  src/style.rs
Labels: usability, code quality

#152 Improve Errors
  RELEASES.md
  examples/basic.rs
  examples/nested.rs
  src/error.rs
  src/lib.rs
  src/node.rs
  src/prelude.rs
Labels: usability

#144 Replace Number type with a simpler Option<f32>
  RELEASES.md
  examples/basic.rs
  examples/nested.rs
  src/flexbox.rs
  src/forest.rs
  src/geometry.rs
  src/layout.rs
  src/lib.rs
  src/math.rs
  src/node.rs
  src/number.rs
  src/prelude.rs
  src/style.rs
  tests/measure.rs
  tests/relayout.rs
  tests/root_constraints.rs
  tests/simple_child.rs
Labels: usability, code quality, breaking-change

#156 Remove solved todo note
  src/node.rs
Labels: code quality

#157 Make `MeasureFunc` Send and Sync
  RELEASES.md
  src/node.rs
Labels: usability, breaking-change

#159 Correctly test that MeasureFunc is Send and Sync
  src/node.rs
Labels: code quality

#161 Remove manual map implementation in `MaybeMath`
  src/math.rs
Labels: code quality, controversial

#172 Setup dependencies CI
  .github/workflows/dependencies.yml
  deny.toml
Labels: build system

#173 Add unit-tests to `resolve`
  src/geometry.rs
  src/style.rs
Labels: code quality

#175 Fix new clippy lints
  src/geometry.rs
Labels: code quality

#181 Add and cleanup new leaf-nodes methods
  RELEASES.md
  src/forest.rs
  src/node.rs
  tests/measure.rs
  tests/node.rs
Labels: usability, breaking-change

#178 Add unit-tests to `node::Taffy`
  src/indexmap.rs
  src/node.rs
  tests/node.rs
Labels: code quality

#174 Additional tests for FlexboxLayout and FlexDirection
  src/geometry.rs
  src/style.rs
Labels: code quality

#169 Added unreachable macro to alleged unreachable code rather than using hidden default value
  src/flexbox.rs
  src/style.rs
Labels: code quality

#185 Add guideline to write tests
  CONTRIBUTING.md
Labels: documentation, meta

#184 Unit test `compute_constants()`
  RELEASES.md
  src/flexbox.rs
  src/geometry.rs
  src/layout.rs
  src/lib.rs
  src/node.rs
  src/resolve.rs
  src/style.rs
Labels: code quality, breaking-change

#194 Cleanup `new_with_children()` uses
  benches/complex.rs
  examples/basic.rs
  examples/nested.rs
  scripts/gentest/src/main.rs
  src/node.rs
  tests/measure.rs
  tests/relayout.rs
  tests/root_constraints.rs
  tests/simple_child.rs
Labels: code quality

#193 Forest unit tests
  src/forest.rs
  src/node.rs
Labels: code quality
