Repository DioxusLabs/taffy, pull requests merged in 2022-05, with the labels that each got.

#37 Add pull request template
  .github/linters/.markdown-lint.yml
  .github/pull_request_template.md
Labels: meta

#36 Add CI jobs for checking and testing with no default features
  .github/workflows/ci.yml
  src/sys.rs
Labels: code quality, build system

#35 Fix Markdown linting in CI
  .github/linters/.markdown-lint.yml
  .github/workflows/ci.yml
  README.md
  bindings/swift/Example/Pods/Nimble/README.md
  bindings/swift/Example/Pods/Quick/README.md
  bindings/swift/Example/Pods/Target Support Files/Pods-StretchKit_Tests/Pods-StretchKit_Tests-acknowledgements.markdown
Labels: bug, build system

#15 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: meta

#52 Update authors field
  Cargo.toml
Labels: bug, meta

#55 Improve PR template
  .github/pull_request_template.md
Labels: meta

#58 Make PR template clearer and shorter
  .github/pull_request_template.md
Labels: meta

#61 Bump version numbers of dependencies
  Cargo.toml
  RELEASES.md
Labels: code quality

#67 Setup and enable dependabot
  .github/dependabot.yml
Labels: build system

#63 Pin *all* the versions!
  rust-toolchain.toml
Labels: meta, build system
