Repository DioxusLabs/taffy, pull requests merged in 2023-07, with the labels that each got.

#505 Minor: fixed comment for geometry::Point type
  src/geometry.rs
Labels: documentation

#511 Remove "parent" references to a node when removing that node
  src/tree/taffy_tree/tree.rs
Labels: bug

#516 Minor: `CellOccupancyMatrix::is_area_in_range()` now immutable
  src/compute/grid/types/cell_occupancy.rs
Labels: code quality

#515 Minor: replaced `Result<(), TaffyError>` by `TaffyResult<()>` for consistency
  src/tree/taffy_tree/tree.rs
Labels: code quality

#521 Fix rounding accumulation bug
  src/compute/taffy_tree.rs
  src/tree/node.rs
  src/tree/taffy_tree/tree.rs
  tests/relayout.rs
Labels: bug
