Repository DioxusLabs/taffy, pull requests merged in 2023-01, with the labels that each got.

#311 Fix using column variable for row calculation
  src/compute/grid/mod.rs
Labels: bug

#314 Fix percent sized tracks
  benches/generated/grid_percent_items_nested_moderate.rs
  benches/generated/grid_percent_items_nested_with_padding_margin.rs
  benches/generated/grid_percent_items_width_and_margin.rs
  benches/generated/grid_percent_items_width_and_padding.rs
  benches/generated/grid_percent_tracks_definite_overflow.rs
  benches/generated/grid_percent_tracks_definite_underflow.rs
  benches/generated/grid_percent_tracks_indefinite_only.rs
  benches/generated/grid_percent_tracks_indefinite_with_content_overflow.rs
  benches/generated/grid_percent_tracks_indefinite_with_content_underflow.rs
  benches/generated/mod.rs
  src/compute/grid/mod.rs
  src/style/dimension.rs
  src/style/grid.rs
  test_fixtures/grid_percent_items_nested_moderate.html
  test_fixtures/grid_percent_items_nested_with_padding_margin.html
  test_fixtures/grid_percent_items_width_and_margin.html
  test_fixtures/grid_percent_items_width_and_padding.html
  test_fixtures/grid_percent_tracks_definite_overflow.html
  test_fixtures/grid_percent_tracks_definite_underflow.html
  test_fixtures/grid_percent_tracks_indefinite_only.html
  test_fixtures/grid_percent_tracks_indefinite_with_content_overflow.html
  test_fixtures/grid_percent_tracks_indefinite_with_content_underflow.html
  tests/generated/grid_percent_items_nested_moderate.rs
  tests/generated/grid_percent_items_nested_with_padding_margin.rs
  tests/generated/grid_percent_items_width_and_margin.rs
  tests/generated/grid_percent_items_width_and_padding.rs
  tests/generated/grid_percent_tracks_definite_overflow.rs
  tests/generated/grid_percent_tracks_definite_underflow.rs
  tests/generated/grid_percent_tracks_indefinite_only.rs
  tests/generated/grid_percent_tracks_indefinite_with_content_overflow.rs
  tests/generated/grid_percent_tracks_indefinite_with_content_underflow.rs
  tests/generated/mod.rs
Labels: bug

#325 Fix flexbox baseline alignment
  benches/generated/align_baseline_child_margin.rs
  benches/generated/align_baseline_child_margin_percent.rs
  benches/generated/align_baseline_child_multiline_no_override_on_secondline.rs
  benches/generated/align_baseline_child_multiline_override.rs
  benches/generated/align_baseline_child_padding.rs
  benches/generated/align_baseline_multiline.rs
  benches/generated/align_baseline_multiline_row_and_column.rs
  benches/generated/mod.rs
  src/compute/flexbox.rs
  src/compute/grid/alignment.rs
  src/compute/grid/mod.rs
  src/compute/grid/types/grid_item.rs
  src/compute/leaf.rs
  src/compute/mod.rs
  src/geometry.rs
  src/layout.rs
  src/prelude.rs
  test_fixtures/align_baseline_child_margin.html
  test_fixtures/align_baseline_child_margin_percent.html
  test_fixtures/align_baseline_child_multiline_no_override_on_secondline.html
  test_fixtures/align_baseline_child_multiline_override.html
  test_fixtures/align_baseline_child_padding.html
  test_fixtures/align_baseline_multiline.html
  test_fixtures/align_baseline_multiline_row_and_column.html
  test_fixtures/xgrid_align_items_baseline_complex.html
  tests/generated/align_baseline_child_margin.rs
  tests/generated/align_baseline_child_margin_percent.rs
  tests/generated/align_baseline_child_multiline_no_override_on_secondline.rs
  tests/generated/align_baseline_child_multiline_override.rs
  tests/generated/align_baseline_child_padding.rs
  tests/generated/align_baseline_multiline.rs
  tests/generated/align_baseline_multiline_row_and_column.rs
  tests/generated/mod.rs
Labels: bug

#329 Fix justify content with margin tests
  benches/generated/justify_content_column_min_height_and_margin.rs
  benches/generated/justify_content_colunn_max_height_and_margin.rs
  benches/generated/mod.rs
  benches/generated/position_root_with_rtl_should_position_withoutdirection.rs
  test_fixtures/justify_content_column_min_height_and_margin.html
  test_fixtures/justify_content_colunn_max_height_and_margin.html
  test_fixtures/position_root_with_rtl_should_position_withoutdirection.html
  test_fixtures/xjustify_content_column_min_height_and_margin.html
  test_fixtures/xjustify_content_colunn_max_height_and_margin.html
  test_fixtures/xposition_root_with_rtl_should_position_withoutdirection.html
  tests/generated/justify_content_column_min_height_and_margin.rs
  tests/generated/justify_content_colunn_max_height_and_margin.rs
  tests/generated/mod.rs
  tests/generated/position_root_with_rtl_should_position_withoutdirection.rs
Labels: testing

#337 Implement head-to-head benchmarks against Yoga
  Cargo.toml
  README.md
  benches/big_tree.rs
  benches/yoga_helpers.rs
  deny.toml
  src/style/dimension.rs
Labels: performance

#338 Optimise CSS Grid
  benches/big_tree_grid.rs
  src/compute/flexbox.rs
  src/compute/grid/explicit_grid.rs
  src/compute/grid/mod.rs
  src/compute/grid/track_sizing.rs
  src/compute/grid/types/grid_item.rs
  src/compute/mod.rs
  src/data.rs
  src/layout.rs
  src/style/grid.rs
  tests/caching.rs
  tests/measure.rs
Labels: performance
