Repository DioxusLabs/taffy, pull requests merged in 2023-04, with the labels that each got.

#413 Optimise flexbox layouts with min/max sizes
  src/compute/flexbox.rs
  src/style/dimension.rs
  test_fixtures/flex_grow_within_constrained_min_max_column.html
  tests/generated/flex_grow_within_constrained_min_max_column.rs
Labels: code quality, performance

#419 Prepare for 0.3.11 release
  Cargo.toml
  RELEASES.md
Labels: release

#414 Moving flexbox behind a feature flag
  .github/workflows/ci.yml
  Cargo.toml
  RELEASES.md
  src/compute/mod.rs
  src/debug.rs
  src/geometry.rs
  src/prelude.rs
  src/style/mod.rs
Labels: usability, breaking-change

#415 Remove `layout_flexbox` function from prelude
  RELEASES.md
  src/prelude.rs
Labels: usability, breaking-change

#427 Trampoline child measurement/layout through the `LayoutTree` trait
  src/compute/flexbox.rs
  src/compute/grid/alignment.rs
  src/compute/grid/mod.rs
  src/compute/grid/track_sizing.rs
  src/compute/grid/types/grid_item.rs
  src/node.rs
  src/tree.rs
Labels: enhancement, usability, breaking-change

#424 Support `Overflow::Hidden`
  scripts/gentest/src/main.rs
  scripts/gentest/test_helper.js
  src/compute/flexbox.rs
  src/compute/grid/track_sizing.rs
  src/compute/grid/types/grid_item.rs
  src/geometry.rs
  src/style/mod.rs
  test_fixtures/do_not_clamp_height_of_absolute_node_to_height_of_its_overflow_hidden_parent.html
  test_fixtures/grid_fit_content_percent_indefinite_max_content_hidden.html
  test_fixtures/grid_fit_content_percent_indefinite_min_content_hidden.html
  test_fixtures/grid_fit_content_points_min_content_hidden.html
  test_fixtures/grid_overflow_inline_axis_hidden.html
  test_fixtures/grid_overflow_inline_axis_visible.html
  test_fixtures/grid_span_13_most_non_flex_with_minmax_indefinite_hidden.html
  test_fixtures/grid_span_2_max_content_auto_indefinite_hidden.html
  test_fixtures/grid_span_2_max_content_fit_content_10px_indefinite_hidden.html
  test_fixtures/grid_span_2_max_content_fit_content_80px_indefinite_hidden.html
  test_fixtures/grid_span_2_min_content_auto_indefinite_hidden.html
  test_fixtures/grid_span_2_min_content_fit_content_10px_indefinite_hidden.html
  test_fixtures/grid_span_2_min_content_fit_content_30px_indefinite_hidden.html
  test_fixtures/grid_span_2_min_content_fit_content_80px_indefinite_hidden.html
  test_fixtures/grid_span_6_all_non_flex_indefinite_hidden.html
  test_fixtures/measure_child_with_flex_shrink_hidden.html
  test_fixtures/overflow_main_axis_shrink_hidden.html
  test_fixtures/overflow_main_axis_shrink_visible.html
  test_fixtures/xflex_basis_zero_undefined_main_size_hidden.html
  tests/caching.rs
  tests/generated/do_not_clamp_height_of_absolute_node_to_height_of_its_overflow_hidden_parent.rs
  tests/generated/grid_fit_content_percent_indefinite_max_content_hidden.rs
  tests/generated/grid_fit_content_percent_indefinite_min_content_hidden.rs
  tests/generated/grid_fit_content_points_min_content_hidden.rs
  tests/generated/grid_overflow_inline_axis_hidden.rs
  tests/generated/grid_overflow_inline_axis_visible.rs
  tests/generated/grid_percent_items_nested_moderate.rs
  tests/generated/grid_span_13_most_non_flex_with_minmax_indefinite_hidden.rs
  tests/generated/grid_span_2_max_content_auto_indefinite_hidden.rs
  tests/generated/grid_span_2_max_content_fit_content_10px_indefinite_hidden.rs
  tests/generated/grid_span_2_max_content_fit_content_80px_indefinite_hidden.rs
  tests/generated/grid_span_2_min_content_auto_indefinite_hidden.rs
  tests/generated/grid_span_2_min_content_fit_content_10px_indefinite_hidden.rs
  tests/generated/grid_span_2_min_content_fit_content_30px_indefinite_hidden.rs
  tests/generated/grid_span_2_min_content_fit_content_80px_indefinite_hidden.rs
  tests/generated/grid_span_6_all_non_flex_indefinite_hidden.rs
  tests/generated/measure_child_with_flex_shrink_hidden.rs
  tests/generated/mod.rs
  tests/generated/overflow_main_axis_shrink_hidden.rs
  tests/generated/overflow_main_axis_shrink_visible.rs
  tests/generated/percentage_moderate_complexity.rs
Labels: enhancement, breaking-change

#431 Remove `cache_mut`, `needs_measure` and `measure_node` methods from `LayoutTree` trait
  RELEASES.md
  src/compute/leaf.rs
  src/compute/mod.rs
  src/node.rs
  src/tree.rs
Labels: usability, breaking-change

#434 Make low-level layout algorithm functions public
  src/compute/flexbox.rs
  src/compute/grid/mod.rs
  src/compute/mod.rs
  src/lib.rs
  src/tree.rs
Labels: enhancement, usability

#436 Fix yoga benchmarks
  Cargo.toml
  benches/flexbox.rs
Labels: bug, benchmarks

#448 Add `taffy_tree` flag to opt-out of default Taffy tree
  Cargo.toml
  src/compute/leaf.rs
  src/compute/mod.rs
  src/compute/taffy_tree.rs
  src/lib.rs
  src/prelude.rs
  src/tree/measure_func.rs
  src/tree/mod.rs
  src/tree/node.rs
  src/tree/taffy_tree/error.rs
  src/tree/taffy_tree/mod.rs
  src/tree/taffy_tree/tree.rs
  src/util/debug.rs
Labels: code quality, breaking-change

#453 Enable `taffy_tree` feature when running tests in CI
  .github/workflows/ci.yml
  src/compute/taffy_tree.rs
Labels: bug, build system

#451 Move benchmarks into their own crate
  .cargo/config.toml
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Cargo.toml
  benches/Cargo.toml
  benches/benches/flexbox.rs
  benches/benches/grid.rs
  benches/benches/tree_creation.rs
  benches/dummy_benchmark.rs
  benches/src/lib.rs
  benches/src/random_style.rs
  benches/src/yoga_helpers.rs
  src/util/mod.rs
Labels: usability, build system, benchmarks

#454 Fix `display:none` caching issue
  src/compute/mod.rs
  src/compute/taffy_tree.rs
  tests/relayout.rs
Labels: bug

#456 Fix caching of `display:none` nodes (backport of #454 to 0.3.x)
  src/compute/mod.rs
  tests/relayout.rs
Labels: bug, backport

#458 Prepare for 0.3.12 release
  Cargo.toml
  RELEASES.md
Labels: release

#461 Remove caching from CI
  .github/workflows/ci.yml
Labels: build system

#462 Remove `rstest` dependency
  Cargo.toml
  src/util/math.rs
  src/util/resolve.rs
Labels: build system, testing

#463 CI: optimise markdown linting
  .github/workflows/ci.yml
  .markdownlint.yml
Labels: build system

#464 Rename inconsistently named gap test
  .gitignore
  test_fixtures/gap_row_gap_percentage_wrapping.html
  tests/generated/gap_row_gap_percentage_wrapping.rs
  tests/generated/mod.rs
Labels: code quality, testing

#466 CI: use the cargo sparse index protocol
  .github/workflows/ci.yml
Labels: build system

#469 Remove duplicate types definitions (`Layout`, `RunMode`, `SizingMode`, `SizeAndBaselines`)
  src/tree/layout.rs
  src/tree/mod.rs
Labels: code quality

#471 Fix yoga benchmark feature flag
  benches/Cargo.toml
  benches/benches/flexbox.rs
  benches/benches/tree_creation.rs
  benches/src/lib.rs
Labels: bug, benchmarks
