Repository DioxusLabs/taffy, pull requests merged in 2023-02, with the labels that each got.

#342 Grid: Add support for repeat() with an integer repetition count
  benches/generated/grid_repeat_integer.rs
  benches/generated/grid_repeat_mixed.rs
  benches/generated/mod.rs
  scripts/gentest/src/main.rs
  src/compute/grid/explicit_grid.rs
  src/style/grid.rs
  src/style_helpers.rs
  test_fixtures/grid_repeat_integer.html
  test_fixtures/grid_repeat_mixed.html
  tests/generated/grid_repeat_integer.rs
  tests/generated/grid_repeat_mixed.rs
  tests/generated/mod.rs
Labels: usability

#344 Grid: baseline alignment support
  benches/generated/grid_align_items_baseline.rs
  benches/generated/grid_align_items_baseline_child.rs
  benches/generated/grid_align_items_baseline_child_margin.rs
  benches/generated/grid_align_items_baseline_child_margin_percent.rs
  benches/generated/grid_align_items_baseline_child_multiline.rs
  benches/generated/grid_align_items_baseline_child_multiline_no_override_on_secondline.rs
  benches/generated/grid_align_items_baseline_child_multiline_override.rs
  benches/generated/grid_align_items_baseline_child_padding.rs
  benches/generated/grid_align_items_baseline_child_top.rs
  benches/generated/grid_align_items_baseline_child_top2.rs
  benches/generated/grid_align_items_baseline_complex.rs
  benches/generated/grid_align_items_baseline_double_nested_child.rs
  benches/generated/grid_align_items_baseline_multiline.rs
  benches/generated/grid_align_items_baseline_multiline_column.rs
  benches/generated/grid_align_items_baseline_multiline_row_and_column.rs
  benches/generated/grid_align_items_baseline_nested_column.rs
  benches/generated/mod.rs
  src/compute/grid/alignment.rs
  src/compute/grid/mod.rs
  src/compute/grid/placement.rs
  src/compute/grid/track_sizing.rs
  src/compute/grid/types/grid_item.rs
  test_fixtures/grid_align_items_baseline.html
  test_fixtures/grid_align_items_baseline_child.html
  test_fixtures/grid_align_items_baseline_child_margin.html
  test_fixtures/grid_align_items_baseline_child_margin_percent.html
  test_fixtures/grid_align_items_baseline_child_multiline.html
  test_fixtures/grid_align_items_baseline_child_multiline_no_override_on_secondline.html
  test_fixtures/grid_align_items_baseline_child_multiline_override.html
  test_fixtures/grid_align_items_baseline_child_padding.html
  test_fixtures/grid_align_items_baseline_child_top.html
  test_fixtures/grid_align_items_baseline_child_top2.html
  test_fixtures/grid_align_items_baseline_complex.html
  test_fixtures/grid_align_items_baseline_double_nested_child.html
  test_fixtures/grid_align_items_baseline_multiline.html
  test_fixtures/grid_align_items_baseline_multiline_column.html
  test_fixtures/grid_align_items_baseline_multiline_row_and_column.html
  test_fixtures/grid_align_items_baseline_nested_column.html
  tests/generated/grid_align_items_baseline.rs
  tests/generated/grid_align_items_baseline_child.rs
  tests/generated/grid_align_items_baseline_child_margin.rs
  tests/generated/grid_align_items_baseline_child_margin_percent.rs
  tests/generated/grid_align_items_baseline_child_multiline.rs
  tests/generated/grid_align_items_baseline_child_multiline_no_override_on_secondline.rs
  tests/generated/grid_align_items_baseline_child_multiline_override.rs
  tests/generated/grid_align_items_baseline_child_padding.rs
  tests/generated/grid_align_items_baseline_child_top.rs
  tests/generated/grid_align_items_baseline_child_top2.rs
  tests/generated/grid_align_items_baseline_complex.rs
  tests/generated/grid_align_items_baseline_double_nested_child.rs
  tests/generated/grid_align_items_baseline_multiline.rs
  tests/generated/grid_align_items_baseline_multiline_column.rs
  tests/generated/grid_align_items_baseline_multiline_row_and_column.rs
  tests/generated/grid_align_items_baseline_nested_column.rs
  tests/generated/mod.rs
Labels: enhancement

#352 Update wrong css in test
  benches/generated/grid_align_items_baseline_child_multiline_override.rs
  test_fixtures/grid_align_items_baseline_child_multiline_override.html
  tests/generated/grid_align_items_baseline_child_multiline_override.rs
Labels: code quality

#354 Implement §9.9.1. Flex Container Intrinsic Main Sizes
  benches/generated/intrinsic_sizing_cross_size_column.rs
  benches/generated/intrinsic_sizing_main_size_column.rs
  benches/generated/intrinsic_sizing_main_size_column_nested.rs
  benches/generated/intrinsic_sizing_main_size_column_wrap.rs
  benches/generated/intrinsic_sizing_main_size_row.rs
  benches/generated/intrinsic_sizing_main_size_row_nested.rs
  benches/generated/intrinsic_sizing_main_size_row_wrap.rs
  benches/generated/mod.rs
  benches/generated/percentage_moderate_complexity2.rs
  benches/generated/simple_child.rs
  src/compute/flexbox.rs
  src/geometry.rs
  test_fixtures/intrinsic_sizing_cross_size_column.html
  test_fixtures/intrinsic_sizing_main_size_column.html
  test_fixtures/intrinsic_sizing_main_size_column_nested.html
  test_fixtures/intrinsic_sizing_main_size_column_wrap.html
  test_fixtures/intrinsic_sizing_main_size_row.html
  test_fixtures/intrinsic_sizing_main_size_row_nested.html
  test_fixtures/intrinsic_sizing_main_size_row_wrap.html
  test_fixtures/percentage_moderate_complexity2.html
  test_fixtures/simple_child.html
  tests/generated/intrinsic_sizing_cross_size_column.rs
  tests/generated/intrinsic_sizing_main_size_column.rs
  tests/generated/intrinsic_sizing_main_size_column_nested.rs
  tests/generated/intrinsic_sizing_main_size_column_wrap.rs
  tests/generated/intrinsic_sizing_main_size_row.rs
  tests/generated/intrinsic_sizing_main_size_row_nested.rs
  tests/generated/intrinsic_sizing_main_size_row_wrap.rs
  tests/generated/mod.rs
  tests/generated/percentage_moderate_complexity2.rs
  tests/generated/simple_child.rs
  tests/simple_child.rs
Labels: bug

#355 Grid: Fix sizing issues in complex cases
  benches/generated/grid_percent_item_inside_stretch_item.rs
  benches/generated/grid_percent_items_nested_inside_stretch_alignment.rs
  benches/generated/grid_percent_items_nested_with_margin.rs
  benches/generated/gridflex_column_integration.rs
  benches/generated/gridflex_kitchen_sink.rs
  benches/generated/gridflex_kitchen_sink_minimise.rs
  benches/generated/gridflex_kitchen_sink_minimise2.rs
  benches/generated/gridflex_kitchen_sink_minimise3.rs
  benches/generated/gridflex_row_integration.rs
  benches/generated/mod.rs
  src/compute/grid/alignment.rs
  src/compute/grid/mod.rs
  src/compute/grid/placement.rs
  src/compute/grid/track_sizing.rs
  src/compute/grid/types/grid_item.rs
  src/compute/mod.rs
  test_fixtures/grid_percent_item_inside_stretch_item.html
  test_fixtures/grid_percent_items_nested_inside_stretch_alignment.html
  test_fixtures/grid_percent_items_nested_with_margin.html
  test_fixtures/gridflex_column_integration.html
  test_fixtures/gridflex_kitchen_sink.html
  test_fixtures/gridflex_kitchen_sink_minimise.html
  test_fixtures/gridflex_kitchen_sink_minimise2.html
  test_fixtures/gridflex_kitchen_sink_minimise3.html
  test_fixtures/gridflex_row_integration.html
  tests/generated/grid_percent_item_inside_stretch_item.rs
  tests/generated/grid_percent_items_nested_inside_stretch_alignment.rs
  tests/generated/grid_percent_items_nested_with_margin.rs
  tests/generated/gridflex_column_integration.rs
  tests/generated/gridflex_kitchen_sink.rs
  tests/generated/gridflex_kitchen_sink_minimise.rs
  tests/generated/gridflex_kitchen_sink_minimise2.rs
  tests/generated/gridflex_kitchen_sink_minimise3.rs
  tests/generated/gridflex_row_integration.rs
  tests/generated/mod.rs
Labels: bug

#350 Grid: Rename Flex to Fraction
  RELEASES.md
  benches/big_tree_grid.rs
  benches/generated/grid_auto_takes_precedence_over_fr.rs
  benches/generated/grid_fr_fixed_size_no_content_proportions.rs
  benches/generated/grid_fr_fixed_size_no_content_proportions_sub_1_sum.rs
  benches/generated/grid_fr_fixed_size_single_item.rs
  benches/generated/grid_fr_no_sized_items_indefinite.rs
  benches/generated/grid_fr_single_item_indefinite.rs
  benches/generated/grid_fr_span_2_proportion.rs
  benches/generated/grid_fr_span_2_proportion_sub_1_sum.rs
  benches/generated/grid_fr_span_2_proportion_with_non_spanned_track.rs
  benches/generated/grid_fr_span_2_proportion_zero_sum.rs
  benches/generated/grid_fr_span_2_proportion_zero_sum_with_non_spanned_track.rs
  benches/generated/grid_min_content_flex_single_item.rs
  benches/generated/grid_min_content_flex_single_item_margin_auto.rs
  benches/generated/grid_min_content_flex_single_item_margin_fixed.rs
  benches/generated/grid_min_content_flex_single_item_margin_percent.rs
  benches/generated/grid_minmax_column_with_fr_fixed.rs
  benches/generated/grid_minmax_max_content_1fr.rs
  benches/generated/grid_minmax_min_content_1fr.rs
  benches/generated/grid_percent_items_nested_with_padding_margin.rs
  benches/generated/grid_span_8_all_track_types_indefinite.rs
  benches/generated/gridflex_column_integration.rs
  benches/generated/gridflex_kitchen_sink.rs
  benches/generated/gridflex_kitchen_sink_minimise.rs
  benches/generated/gridflex_row_integration.rs
  examples/grid_holy_grail.rs
  scripts/gentest/src/main.rs
  src/compute/grid/explicit_grid.rs
  src/compute/grid/track_sizing.rs
  src/compute/grid/types/grid_item.rs
  src/compute/grid/types/grid_track.rs
  src/compute/grid/util/test_helpers.rs
  src/prelude.rs
  src/style/grid.rs
  src/style_helpers.rs
  tests/generated/grid_auto_takes_precedence_over_fr.rs
  tests/generated/grid_fr_fixed_size_no_content_proportions.rs
  tests/generated/grid_fr_fixed_size_no_content_proportions_sub_1_sum.rs
  tests/generated/grid_fr_fixed_size_single_item.rs
  tests/generated/grid_fr_no_sized_items_indefinite.rs
  tests/generated/grid_fr_single_item_indefinite.rs
  tests/generated/grid_fr_span_2_proportion.rs
  tests/generated/grid_fr_span_2_proportion_sub_1_sum.rs
  tests/generated/grid_fr_span_2_proportion_with_non_spanned_track.rs
  tests/generated/grid_fr_span_2_proportion_zero_sum.rs
  tests/generated/grid_fr_span_2_proportion_zero_sum_with_non_spanned_track.rs
  tests/generated/grid_min_content_flex_single_item.rs
  tests/generated/grid_min_content_flex_single_item_margin_auto.rs
  tests/generated/grid_min_content_flex_single_item_margin_fixed.rs
  tests/generated/grid_min_content_flex_single_item_margin_percent.rs
  tests/generated/grid_minmax_column_with_fr_fixed.rs
  tests/generated/grid_minmax_max_content_1fr.rs
  tests/generated/grid_minmax_min_content_1fr.rs
  tests/generated/grid_percent_items_nested_with_padding_margin.rs
  tests/generated/grid_span_8_all_track_types_indefinite.rs
  tests/generated/gridflex_column_integration.rs
  tests/generated/gridflex_kitchen_sink.rs
  tests/generated/gridflex_kitchen_sink_minimise.rs
  tests/generated/gridflex_row_integration.rs
Labels: usability, breaking-change

#361 Avoid performing layout when computing size and size is known from styles
  src/compute/flexbox.rs
Labels: performance

#357 WIP: 0.3.0 release
  .github/linters/.markdown-lint.yml
  Cargo.toml
  README.md
  RELEASES.md
  benches/results-2022-12-07.md
  benches/results-2023-02-08.md
Labels: release

#365 Update 0.3.x branch with 0.3.1 changes
  .github/workflows/ci.yml
  Cargo.toml
  RELEASES.md
  src/compute/grid/types/coordinates.rs
  src/geometry.rs
  src/style/grid.rs
Labels: release

#375 Prepare for 0.3.3 release
  Cargo.toml
  RELEASES.md
Labels: release
