Repository DioxusLabs/taffy, pull requests merged in 2023-08, with the labels that each got.

#522 Flexbox: pass correct cross-axis available space when computing an item's intrinsic main size (+misc fixes)
  src/compute/flexbox.rs
  src/compute/leaf.rs
  test_fixtures/bevy_issue_9530.html
  test_fixtures/bevy_issue_9530_reduced.html
  test_fixtures/bevy_issue_9530_reduced2.html
  test_fixtures/bevy_issue_9530_reduced3.html
  test_fixtures/bevy_issue_9530_reduced4.html
  tests/generated/bevy_issue_9530.rs
  tests/generated/bevy_issue_9530_reduced.rs
  tests/generated/bevy_issue_9530_reduced2.rs
  tests/generated/bevy_issue_9530_reduced3.rs
  tests/generated/bevy_issue_9530_reduced4.rs
  tests/generated/mod.rs
Labels: bug

#512 Minor: added docs & test-case for updated 'Taffy::remove()' behaviour
  src/tree/taffy_tree/tree.rs
Labels: code quality

#526 Fix commented out variant of basic example
  examples/basic.rs
Labels: documentation

#491 Fix: Make CSS Grid algorithm correctly apply max width/height and available space when it is the root node
  scripts/gentest/src/main.rs
  scripts/gentest/test_base_style.css
  scripts/gentest/test_helper.js
  src/compute/grid/mod.rs
  src/compute/grid/track_sizing.rs
  test_fixtures/grid_available_space_greater_than_max_content.html
  test_fixtures/grid_available_space_smaller_than_max_content.html
  test_fixtures/grid_available_space_smaller_than_min_content.html
  test_fixtures/grid_max_width_greater_than_max_content.html
  test_fixtures/grid_max_width_less_than_max_content_with_min_content.html
  test_fixtures/grid_max_width_smaller_than_max_content.html
  test_fixtures/grid_max_width_smaller_than_min_content.html
  tests/generated/grid_available_space_greater_than_max_content.rs
  tests/generated/grid_available_space_smaller_than_max_content.rs
  tests/generated/grid_available_space_smaller_than_min_content.rs
  tests/generated/grid_max_width_greater_than_max_content.rs
  tests/generated/grid_max_width_less_than_max_content_with_min_content.rs
  tests/generated/grid_max_width_smaller_than_max_content.rs
  tests/generated/grid_max_width_smaller_than_min_content.rs
  tests/generated/mod.rs
Labels: bug

#527 Update main branch changelog for the v0.3.13 release
  RELEASES.md
Labels: documentation, release
