Repository DioxusLabs/taffy, pull requests merged in 2024-02, with the labels that each got.

#610 Fix docs copy-paste error
  src/lib.rs
Labels: documentation

#604 Document low-level traits
  src/compute/mod.rs
  src/lib.rs
  src/tree/traits.rs
Labels: documentation

#615 Upgrade cosmic_text example to cosmic-text 0.11.2
  Cargo.toml
  examples/cosmic_text.rs
Labels: documentation, dependencies

#619 Add parent method to the TaffyTree
  src/tree/taffy_tree.rs
Labels: usability

#618 Prepare for v0.4.0 release
  Cargo.toml
  RELEASES.md
Labels: release

#621 Add more users and bindings to README
  README.md
Labels: documentation
