Repository DioxusLabs/taffy, pull requests merged in 2024-12, with the labels that each got.

#748 Add params to bench justfile task
  justfile
Labels: build system

#747 Block: ignore margin collapsing when computing static position of abspos items
  src/compute/block.rs
Labels: bug

#753 Prepare for v0.6.3 release
  CHANGELOG.md
  Cargo.toml
Labels: release

#754 Move cosmic-text example into it's own crate
  .github/workflows/ci.yml
  Cargo.toml
  examples/cosmic_text/Cargo.toml
  examples/cosmic_text/src/image.rs
  examples/cosmic_text/src/main.rs
Labels: testing

#756 Remove duplicate detection skips from `deny.toml`
  deny.toml
Labels: build system, dependencies

#757 Add content-box helper methods to Layout
  src/tree/layout.rs
Labels: enhancement

#749 TaffyTree::set_children: Remove from previous parent
  src/tree/taffy_tree.rs
Labels: bug

#758 Split out caching into separate `CacheTree` trait
  examples/custom_tree_owned_partial.rs
  examples/custom_tree_owned_unsafe.rs
  examples/custom_tree_vec.rs
  src/compute/mod.rs
  src/tree/taffy_tree.rs
  src/tree/traits.rs
Labels: enhancement, breaking-change

#759 Prepare for v0.7.0 release
  CHANGELOG.md
  Cargo.toml
  benches/benches/flexbox.rs
  benches/src/taffy_helpers.rs
Labels: release

#760 Improve interaction of abspos children of block containers with margin collapsing
  src/compute/block.rs
Labels: bug

#761 Eliminate the `num-traits` dependency
  src/util/sys.rs
Labels: dependencies

#762 Fully remove num-traits
  Cargo.toml
  src/compute/grid/explicit_grid.rs
  src/util/sys.rs
Labels: dependencies

#764 Document that Taffy percentages are represented by the range [0, 1] not [0, 100]
  src/style/dimension.rs
Labels: documentation

#767 Prepare for v0.7.1 release
  CHANGELOG.md
  Cargo.toml
Labels: release
