Repository DioxusLabs/taffy, pull requests merged in 2024-07, with the labels that each got.

#674 Block stretch sizing fixes
  src/compute/block.rs
  src/compute/mod.rs
Labels: bug

#676 Prepare from v0.5.2 release
  Cargo.toml
  RELEASES.md
Labels: release

#677 Include examples in Cargo.toml package
  Cargo.toml
Labels: bug

#678 Output computed margins in `Layout`
  src/compute/block.rs
  src/compute/flexbox.rs
  src/compute/grid/alignment.rs
  src/compute/mod.rs
  src/tree/layout.rs
Labels: enhancement, breaking-change

#666 Absolute Insets should be resolved against the container size minus border
  src/compute/block.rs
  src/compute/flexbox.rs
  src/compute/grid/mod.rs
  test_fixtures/block/block_absolute_resolved_insets.html
  test_fixtures/flex/absolute_resolved_insets.html
  test_fixtures/grid/grid_absolute_resolved_insets.html
  tests/generated/block/block_absolute_resolved_insets.rs
  tests/generated/block/mod.rs
  tests/generated/flex/absolute_resolved_insets.rs
  tests/generated/flex/mod.rs
  tests/generated/grid/grid_absolute_resolved_insets.rs
  tests/generated/grid/mod.rs
Labels: bug

#681 Remove unit tests from flexbox module
  src/compute/flexbox.rs
Labels: code quality, testing

#682 Make it clearer which state is mutable in block layout abspos implementation
  src/compute/block.rs
Labels: code quality

#683 Don't use block layout in flexbox test
  test_fixtures/flex/align_items_center_with_max_height_with_padding_border.html
  tests/generated/flex/align_items_center_with_max_height_with_padding_border.rs
Labels: testing

#686 Increase coverage of serde derives
  src/style/dimension.rs
  src/tree/cache.rs
  src/tree/layout.rs
Labels: enhancement

#687 Add `DEFAULT` constant to LayoutOutput
  src/tree/layout.rs
Labels: enhancement

#688 Impl debug, clone for Cache
  src/tree/cache.rs
Labels: enhancement

#568 "Traitify" the `Style` struct
  examples/custom_tree_owned_partial.rs
  examples/custom_tree_owned_unsafe.rs
  examples/custom_tree_vec.rs
  src/compute/block.rs
  src/compute/flexbox.rs
  src/compute/grid/alignment.rs
  src/compute/grid/explicit_grid.rs
  src/compute/grid/implicit_grid.rs
  src/compute/grid/mod.rs
  src/compute/grid/placement.rs
  src/compute/grid/types/grid_item.rs
  src/compute/leaf.rs
  src/compute/mod.rs
  src/style/flex.rs
  src/style/grid.rs
  src/style/mod.rs
  src/tree/mod.rs
  src/tree/taffy_tree.rs
  src/tree/traits.rs
Labels: enhancement, usability, code quality

#689 Flexbox: Fix flooring hypothetical_main_size by computed min size
  src/compute/flexbox.rs
  test_fixtures/flex/flex_grow_0_min_size.html
  tests/generated/flex/flex_grow_0_min_size.rs
  tests/generated/flex/mod.rs
Labels: bug

#690 Fix flex line cross-size determination
  src/compute/flexbox.rs
  test_fixtures/flex/align_content_space_around_wrapped_single.html
  test_fixtures/flex/align_content_space_between_wrapped_single.html
  test_fixtures/flex/align_content_space_evenly_wrapped_single.html
  test_fixtures/flex/align_content_stretch_row_wrap.html
  tests/generated/flex/align_content_space_around_wrapped_single.rs
  tests/generated/flex/align_content_space_between_wrapped_single.rs
  tests/generated/flex/align_content_space_evenly_wrapped_single.rs
  tests/generated/flex/align_content_stretch_row_wrap.rs
  tests/generated/flex/mod.rs
Labels: bug

#691 Fix panics in the grid algorithm
  src/compute/grid/explicit_grid.rs
  src/compute/grid/placement.rs
  src/compute/grid/track_sizing.rs
Labels: bug

#692 Fix resolving flexible lengths (WPT css/flexbox-multiline-min-max test)
  src/compute/flexbox.rs
  test_fixtures/flex/multiline_min_max_12.html
  test_fixtures/flex/multiline_min_max_13.html
  test_fixtures/flex/multiline_min_max_14.html
  test_fixtures/flex/multiline_min_max_5.html
  test_fixtures/flex/multiline_min_max_8.html
  tests/generated/flex/mod.rs
  tests/generated/flex/multiline_min_max_12.rs
  tests/generated/flex/multiline_min_max_13.rs
  tests/generated/flex/multiline_min_max_14.rs
  tests/generated/flex/multiline_min_max_5.rs
  tests/generated/flex/multiline_min_max_8.rs
Labels: bug

#694 Fix flexbox wrapping when a max main size style is present
  src/compute/flexbox.rs
  test_fixtures/flex/multiline_column_max_height.html
  tests/generated/flex/mod.rs
  tests/generated/flex/multiline_column_max_height.rs
Labels: bug

#695 Fix case where Taffy allowed margins to collapse through an element when it shouldn't have
  src/compute/block.rs
  src/compute/leaf.rs
Labels: bug

#698 Implement legacy text alignment
  scripts/gentest/src/main.rs
  scripts/gentest/test_helper.js
  src/compute/block.rs
  src/compute/flexbox.rs
  src/style/block.rs
  src/style/mod.rs
  src/tree/traits.rs
  test_fixtures/block/block_item_text_align_center.html
  test_fixtures/block/block_item_text_align_left.html
  test_fixtures/block/block_item_text_align_right.html
  tests/generated/block/block_item_text_align_center.rs
  tests/generated/block/block_item_text_align_left.rs
  tests/generated/block/block_item_text_align_right.rs
  tests/generated/block/mod.rs
Labels: enhancement, breaking-change
