Repository DioxusLabs/taffy, pull requests merged in 2024-06, with the labels that each got.

#670 Update cosmic-text example to cosmic-text 0.12
  Cargo.toml
  examples/cosmic_text.rs
Labels: documentation, dependencies

#671 Fix panic when GridLine 0 is specified
  src/style/grid.rs
Labels: bug

#673 Fix computation of intrinsic main size when it depends on a child's known cross size
  src/compute/flexbox.rs
  src/compute/mod.rs
  test_fixtures/flex/blitz_issue_88.html
  tests/generated/flex/blitz_issue_88.rs
  tests/generated/flex/mod.rs
Labels: bug

#672 Document feature flags and scrape examples
  .github/workflows/ci.yml
  Cargo.toml
  src/lib.rs
Labels: documentation
