Repository DioxusLabs/taffy, pull requests merged in 2025-03, with the labels that each got.

#811 Fix clippy::large_enum_variant lint in cosmic-text example
  examples/cosmic_text/src/main.rs
Labels: code quality

#815 Upgrade cosmic-text to 0.13
  .github/workflows/ci.yml
  .gitignore
  Cargo.toml
  examples/cosmic_text/Cargo.toml
Labels: dependencies

#817 fix: removed wrong addition, causing items to be misplaced.
  src/compute/grid/placement.rs
  test_fixtures/grid/grid_placement_definite_primary.html
  tests/generated/grid/grid_placement_definite_primary.rs
  tests/generated/grid/mod.rs
Labels: bug

#818 Fix grid placement for items with fixed primary axis
  src/compute/grid/placement.rs
Labels: bug

#819 Leaf layout: don't set indefinite available space to max-size
  src/compute/leaf.rs
Labels: bug

#822 Doc: ensure detailed grid info types are public / documented
  src/compute/mod.rs
  src/style/mod.rs
Labels: documentation
