Repository DioxusLabs/taffy, pull requests merged in 2025-01, with the labels that each got.

#774 Detailed layout info cleanup
  .github/workflows/ci.yml
  src/lib.rs
  src/tree/layout.rs
  src/tree/taffy_tree.rs
  src/tree/traits.rs
Labels: code quality

#775 Prepare for v0.7.2 release
  CHANGELOG.md
  Cargo.toml
Labels: release

#776 Add Servo as a user of Taffy. List Blitz instead of Dioxus
  README.md
Labels: documentation

#779 Use &self instead of &mut self for detailed_layout_info method
  src/tree/taffy_tree.rs
Labels: bug

#780 Prepare for v0.7.3 release
  CHANGELOG.md
  Cargo.toml
Labels: release

#773 Implement `calc()` in the low-level API
  examples/custom_tree_owned_partial.rs
  examples/custom_tree_owned_unsafe.rs
  examples/custom_tree_vec.rs
  src/compute/block.rs
  src/compute/flexbox.rs
  src/compute/grid/alignment.rs
  src/compute/grid/explicit_grid.rs
  src/compute/grid/mod.rs
  src/compute/grid/track_sizing.rs
  src/compute/grid/types/grid_item.rs
  src/compute/leaf.rs
  src/compute/mod.rs
  src/lib.rs
  src/style/dimension.rs
  src/style/grid.rs
  src/tree/taffy_tree.rs
  src/tree/traits.rs
  src/util/resolve.rs
Labels: enhancement

#781 Reinstate 1.65 MSRV
  .github/workflows/ci.yml
  Cargo.toml
  src/style/dimension.rs
Labels: usability

#782 Expose grid info for empty grid
  src/compute/grid/mod.rs
Labels: bug

#783 Grid: only stretch auto tracks if content-alignment is stretch
  src/compute/grid/mod.rs
  src/compute/grid/track_sizing.rs
Labels: bug

#785 Special-case "compressible replaced elements" in grid sizing algorithm
  src/compute/grid/types/grid_item.rs
  src/style/mod.rs
Labels: bug

#787 Move CompactLength into it's own module
  src/style/compact_length.rs
  src/style/dimension.rs
  src/style/mod.rs
Labels: code quality

#788 Style value constructors
  src/style/dimension.rs
  src/style/grid.rs
Labels: usability

#791 Upgrade `yoga-rs` (benchmark dependency) to v0.5.0
  benches/Cargo.toml
  benches/src/yoga_helpers.rs
Labels: dependencies, benchmarks

#792 Fix infinite loop due to float precision in grid layout maximise tracks step
  src/compute/grid/track_sizing.rs
Labels: bug
